/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
import * as reactQuery from "react-query";
import { useBarsApiContext, BarsApiContext } from "./barsApiContext";
import { barsApiFetch } from "./barsApiFetcher";
import type * as Schemas from "./barsApiSchemas";

export type AppControllerGetHelloResponse = {
  success: boolean;
  /*
   * @default false
   */
  isArray: boolean;
  isPaginated?: boolean;
  isSorted?: boolean;
  isFiltered?: boolean;
  message?: string;
  pagination?: Schemas.PaginationInfoDto;
  sorting?: Schemas.SortingInfoDto;
  filtering?: Schemas.FilteringInfoDto;
  data: never;
};

export type AppControllerGetHelloVariables = BarsApiContext["fetcherOptions"];

export const fetchAppControllerGetHello = (
  variables: AppControllerGetHelloVariables
) =>
  barsApiFetch<AppControllerGetHelloResponse, undefined, {}, {}, {}>({
    url: "/api",
    method: "get",
    ...variables,
  });

export const useAppControllerGetHello = (
  queryKey: reactQuery.QueryKey,
  variables: AppControllerGetHelloVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      AppControllerGetHelloResponse,
      undefined,
      AppControllerGetHelloResponse
    >,
    "queryKey" | "queryFn"
  >
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } = useBarsApiContext();
  return reactQuery.useQuery<
    AppControllerGetHelloResponse,
    undefined,
    AppControllerGetHelloResponse
  >(
    queryKeyFn(queryKey),
    () => fetchAppControllerGetHello({ ...fetcherOptions, ...variables }),
    {
      ...queryOptions,
      ...options,
    }
  );
};

export type AppControllerGetHealthResponse = {
  success: boolean;
  /*
   * @default false
   */
  isArray: boolean;
  isPaginated?: boolean;
  isSorted?: boolean;
  isFiltered?: boolean;
  message?: string;
  pagination?: Schemas.PaginationInfoDto;
  sorting?: Schemas.SortingInfoDto;
  filtering?: Schemas.FilteringInfoDto;
  data: Record<string, any>;
};

export type AppControllerGetHealthVariables = BarsApiContext["fetcherOptions"];

export const fetchAppControllerGetHealth = (
  variables: AppControllerGetHealthVariables
) =>
  barsApiFetch<AppControllerGetHealthResponse, undefined, {}, {}, {}>({
    url: "/api/health",
    method: "get",
    ...variables,
  });

export const useAppControllerGetHealth = (
  queryKey: reactQuery.QueryKey,
  variables: AppControllerGetHealthVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      AppControllerGetHealthResponse,
      undefined,
      AppControllerGetHealthResponse
    >,
    "queryKey" | "queryFn"
  >
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } = useBarsApiContext();
  return reactQuery.useQuery<
    AppControllerGetHealthResponse,
    undefined,
    AppControllerGetHealthResponse
  >(
    queryKeyFn(queryKey),
    () => fetchAppControllerGetHealth({ ...fetcherOptions, ...variables }),
    {
      ...queryOptions,
      ...options,
    }
  );
};

export type AuthControllerRegisterResponse = {
  success: boolean;
  /*
   * @default false
   */
  isArray: boolean;
  isPaginated?: boolean;
  isSorted?: boolean;
  isFiltered?: boolean;
  message?: string;
  pagination?: Schemas.PaginationInfoDto;
  sorting?: Schemas.SortingInfoDto;
  filtering?: Schemas.FilteringInfoDto;
  data: Schemas.AuthResponseDto;
};

export type AuthControllerRegisterVariables = {
  body: Schemas.RegisterDto;
} & BarsApiContext["fetcherOptions"];

export const fetchAuthControllerRegister = (
  variables: AuthControllerRegisterVariables
) =>
  barsApiFetch<AuthControllerRegisterResponse, Schemas.RegisterDto, {}, {}, {}>(
    { url: "/api/auth/register", method: "post", ...variables }
  );

export const useAuthControllerRegister = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      AuthControllerRegisterResponse,
      undefined,
      AuthControllerRegisterVariables
    >,
    "mutationFn"
  >
) => {
  const { fetcherOptions } = useBarsApiContext();
  return reactQuery.useMutation<
    AuthControllerRegisterResponse,
    undefined,
    AuthControllerRegisterVariables
  >(
    (variables: AuthControllerRegisterVariables) =>
      fetchAuthControllerRegister({ ...fetcherOptions, ...variables }),
    options
  );
};

export type AuthControllerLoginResponse = {
  success: boolean;
  /*
   * @default false
   */
  isArray: boolean;
  isPaginated?: boolean;
  isSorted?: boolean;
  isFiltered?: boolean;
  message?: string;
  pagination?: Schemas.PaginationInfoDto;
  sorting?: Schemas.SortingInfoDto;
  filtering?: Schemas.FilteringInfoDto;
  data: Schemas.AuthResponseDto;
};

export type AuthControllerLoginVariables = {
  body: Schemas.LoginDto;
} & BarsApiContext["fetcherOptions"];

export const fetchAuthControllerLogin = (
  variables: AuthControllerLoginVariables
) =>
  barsApiFetch<AuthControllerLoginResponse, Schemas.LoginDto, {}, {}, {}>({
    url: "/api/auth/login",
    method: "post",
    ...variables,
  });

export const useAuthControllerLogin = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      AuthControllerLoginResponse,
      undefined,
      AuthControllerLoginVariables
    >,
    "mutationFn"
  >
) => {
  const { fetcherOptions } = useBarsApiContext();
  return reactQuery.useMutation<
    AuthControllerLoginResponse,
    undefined,
    AuthControllerLoginVariables
  >(
    (variables: AuthControllerLoginVariables) =>
      fetchAuthControllerLogin({ ...fetcherOptions, ...variables }),
    options
  );
};

export type AuthControllerRefreshHeaders = {
  /*
   * Optional: Authorization header in the form "Bearer <refresh-token>"
   *
   * @example Bearer refresh-token-example
   */
  Authorization?: string;
  /*
   * Refresh token (alternative to cookie). Example: refresh-token value
   *
   * @example refresh-token-example
   */
  ["x-refresh-token"]?: string;
};

export type AuthControllerRefreshResponse = {
  success: boolean;
  /*
   * @default false
   */
  isArray: boolean;
  isPaginated?: boolean;
  isSorted?: boolean;
  isFiltered?: boolean;
  message?: string;
  pagination?: Schemas.PaginationInfoDto;
  sorting?: Schemas.SortingInfoDto;
  filtering?: Schemas.FilteringInfoDto;
  data: Schemas.AuthResponseDto;
};

export type AuthControllerRefreshVariables = {
  headers?: AuthControllerRefreshHeaders;
} & BarsApiContext["fetcherOptions"];

export const fetchAuthControllerRefresh = (
  variables: AuthControllerRefreshVariables
) =>
  barsApiFetch<
    AuthControllerRefreshResponse,
    undefined,
    AuthControllerRefreshHeaders,
    {},
    {}
  >({ url: "/api/auth/refresh", method: "post", ...variables });

export const useAuthControllerRefresh = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      AuthControllerRefreshResponse,
      undefined,
      AuthControllerRefreshVariables
    >,
    "mutationFn"
  >
) => {
  const { fetcherOptions } = useBarsApiContext();
  return reactQuery.useMutation<
    AuthControllerRefreshResponse,
    undefined,
    AuthControllerRefreshVariables
  >(
    (variables: AuthControllerRefreshVariables) =>
      fetchAuthControllerRefresh({ ...fetcherOptions, ...variables }),
    options
  );
};

export type AuthControllerLogoutResponse = {
  success: boolean;
  /*
   * @default false
   */
  isArray: boolean;
  isPaginated?: boolean;
  isSorted?: boolean;
  isFiltered?: boolean;
  message?: string;
  pagination?: Schemas.PaginationInfoDto;
  sorting?: Schemas.SortingInfoDto;
  filtering?: Schemas.FilteringInfoDto;
  data: Record<string, any>;
};

export type AuthControllerLogoutVariables = BarsApiContext["fetcherOptions"];

export const fetchAuthControllerLogout = (
  variables: AuthControllerLogoutVariables
) =>
  barsApiFetch<AuthControllerLogoutResponse, undefined, {}, {}, {}>({
    url: "/api/auth/logout",
    method: "post",
    ...variables,
  });

export const useAuthControllerLogout = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      AuthControllerLogoutResponse,
      undefined,
      AuthControllerLogoutVariables
    >,
    "mutationFn"
  >
) => {
  const { fetcherOptions } = useBarsApiContext();
  return reactQuery.useMutation<
    AuthControllerLogoutResponse,
    undefined,
    AuthControllerLogoutVariables
  >(
    (variables: AuthControllerLogoutVariables) =>
      fetchAuthControllerLogout({ ...fetcherOptions, ...variables }),
    options
  );
};

export type AuthControllerChangePasswordResponse = {
  success: boolean;
  /*
   * @default false
   */
  isArray: boolean;
  isPaginated?: boolean;
  isSorted?: boolean;
  isFiltered?: boolean;
  message?: string;
  pagination?: Schemas.PaginationInfoDto;
  sorting?: Schemas.SortingInfoDto;
  filtering?: Schemas.FilteringInfoDto;
  data: Record<string, any>;
};

export type AuthControllerChangePasswordVariables = {
  body: Schemas.ChangePasswordDto;
} & BarsApiContext["fetcherOptions"];

export const fetchAuthControllerChangePassword = (
  variables: AuthControllerChangePasswordVariables
) =>
  barsApiFetch<
    AuthControllerChangePasswordResponse,
    Schemas.ChangePasswordDto,
    {},
    {},
    {}
  >({ url: "/api/auth/change-password", method: "post", ...variables });

export const useAuthControllerChangePassword = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      AuthControllerChangePasswordResponse,
      undefined,
      AuthControllerChangePasswordVariables
    >,
    "mutationFn"
  >
) => {
  const { fetcherOptions } = useBarsApiContext();
  return reactQuery.useMutation<
    AuthControllerChangePasswordResponse,
    undefined,
    AuthControllerChangePasswordVariables
  >(
    (variables: AuthControllerChangePasswordVariables) =>
      fetchAuthControllerChangePassword({ ...fetcherOptions, ...variables }),
    options
  );
};

export type AuthControllerForgotPasswordResponse = {
  success: boolean;
  /*
   * @default false
   */
  isArray: boolean;
  isPaginated?: boolean;
  isSorted?: boolean;
  isFiltered?: boolean;
  message?: string;
  pagination?: Schemas.PaginationInfoDto;
  sorting?: Schemas.SortingInfoDto;
  filtering?: Schemas.FilteringInfoDto;
  data: Record<string, any>;
};

export type AuthControllerForgotPasswordVariables = {
  body: Schemas.ForgotPasswordDto;
} & BarsApiContext["fetcherOptions"];

export const fetchAuthControllerForgotPassword = (
  variables: AuthControllerForgotPasswordVariables
) =>
  barsApiFetch<
    AuthControllerForgotPasswordResponse,
    Schemas.ForgotPasswordDto,
    {},
    {},
    {}
  >({ url: "/api/auth/forgot-password", method: "post", ...variables });

export const useAuthControllerForgotPassword = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      AuthControllerForgotPasswordResponse,
      undefined,
      AuthControllerForgotPasswordVariables
    >,
    "mutationFn"
  >
) => {
  const { fetcherOptions } = useBarsApiContext();
  return reactQuery.useMutation<
    AuthControllerForgotPasswordResponse,
    undefined,
    AuthControllerForgotPasswordVariables
  >(
    (variables: AuthControllerForgotPasswordVariables) =>
      fetchAuthControllerForgotPassword({ ...fetcherOptions, ...variables }),
    options
  );
};

export type AuthControllerResetPasswordResponse = {
  success: boolean;
  /*
   * @default false
   */
  isArray: boolean;
  isPaginated?: boolean;
  isSorted?: boolean;
  isFiltered?: boolean;
  message?: string;
  pagination?: Schemas.PaginationInfoDto;
  sorting?: Schemas.SortingInfoDto;
  filtering?: Schemas.FilteringInfoDto;
  data: Record<string, any>;
};

export type AuthControllerResetPasswordVariables = {
  body: Schemas.ResetPasswordDto;
} & BarsApiContext["fetcherOptions"];

export const fetchAuthControllerResetPassword = (
  variables: AuthControllerResetPasswordVariables
) =>
  barsApiFetch<
    AuthControllerResetPasswordResponse,
    Schemas.ResetPasswordDto,
    {},
    {},
    {}
  >({ url: "/api/auth/reset-password", method: "post", ...variables });

export const useAuthControllerResetPassword = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      AuthControllerResetPasswordResponse,
      undefined,
      AuthControllerResetPasswordVariables
    >,
    "mutationFn"
  >
) => {
  const { fetcherOptions } = useBarsApiContext();
  return reactQuery.useMutation<
    AuthControllerResetPasswordResponse,
    undefined,
    AuthControllerResetPasswordVariables
  >(
    (variables: AuthControllerResetPasswordVariables) =>
      fetchAuthControllerResetPassword({ ...fetcherOptions, ...variables }),
    options
  );
};

export type AuthControllerGetMeResponse = {
  success: boolean;
  /*
   * @default false
   */
  isArray: boolean;
  isPaginated?: boolean;
  isSorted?: boolean;
  isFiltered?: boolean;
  message?: string;
  pagination?: Schemas.PaginationInfoDto;
  sorting?: Schemas.SortingInfoDto;
  filtering?: Schemas.FilteringInfoDto;
  data: Record<string, any>;
};

export type AuthControllerGetMeVariables = BarsApiContext["fetcherOptions"];

export const fetchAuthControllerGetMe = (
  variables: AuthControllerGetMeVariables
) =>
  barsApiFetch<AuthControllerGetMeResponse, undefined, {}, {}, {}>({
    url: "/api/auth/me",
    method: "get",
    ...variables,
  });

export const useAuthControllerGetMe = (
  queryKey: reactQuery.QueryKey,
  variables: AuthControllerGetMeVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      AuthControllerGetMeResponse,
      undefined,
      AuthControllerGetMeResponse
    >,
    "queryKey" | "queryFn"
  >
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } = useBarsApiContext();
  return reactQuery.useQuery<
    AuthControllerGetMeResponse,
    undefined,
    AuthControllerGetMeResponse
  >(
    queryKeyFn(queryKey),
    () => fetchAuthControllerGetMe({ ...fetcherOptions, ...variables }),
    {
      ...queryOptions,
      ...options,
    }
  );
};

export type AuthControllerVerifyResponse = {
  success: boolean;
  /*
   * @default false
   */
  isArray: boolean;
  isPaginated?: boolean;
  isSorted?: boolean;
  isFiltered?: boolean;
  message?: string;
  pagination?: Schemas.PaginationInfoDto;
  sorting?: Schemas.SortingInfoDto;
  filtering?: Schemas.FilteringInfoDto;
  data: Record<string, any>;
};

export type AuthControllerVerifyVariables = BarsApiContext["fetcherOptions"];

export const fetchAuthControllerVerify = (
  variables: AuthControllerVerifyVariables
) =>
  barsApiFetch<AuthControllerVerifyResponse, undefined, {}, {}, {}>({
    url: "/api/auth/verify",
    method: "post",
    ...variables,
  });

export const useAuthControllerVerify = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      AuthControllerVerifyResponse,
      undefined,
      AuthControllerVerifyVariables
    >,
    "mutationFn"
  >
) => {
  const { fetcherOptions } = useBarsApiContext();
  return reactQuery.useMutation<
    AuthControllerVerifyResponse,
    undefined,
    AuthControllerVerifyVariables
  >(
    (variables: AuthControllerVerifyVariables) =>
      fetchAuthControllerVerify({ ...fetcherOptions, ...variables }),
    options
  );
};

export type AuthControllerTestSendEmailResponse = {
  success: boolean;
  /*
   * @default false
   */
  isArray: boolean;
  isPaginated?: boolean;
  isSorted?: boolean;
  isFiltered?: boolean;
  message?: string;
  pagination?: Schemas.PaginationInfoDto;
  sorting?: Schemas.SortingInfoDto;
  filtering?: Schemas.FilteringInfoDto;
  data: Record<string, any>;
};

export type AuthControllerTestSendEmailRequestBody = {
  /*
   * @example test@example.com
   */
  email?: string;
};

export type AuthControllerTestSendEmailVariables = {
  body?: AuthControllerTestSendEmailRequestBody;
} & BarsApiContext["fetcherOptions"];

export const fetchAuthControllerTestSendEmail = (
  variables: AuthControllerTestSendEmailVariables
) =>
  barsApiFetch<
    AuthControllerTestSendEmailResponse,
    AuthControllerTestSendEmailRequestBody,
    {},
    {},
    {}
  >({ url: "/api/auth/test-send-email", method: "post", ...variables });

export const useAuthControllerTestSendEmail = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      AuthControllerTestSendEmailResponse,
      undefined,
      AuthControllerTestSendEmailVariables
    >,
    "mutationFn"
  >
) => {
  const { fetcherOptions } = useBarsApiContext();
  return reactQuery.useMutation<
    AuthControllerTestSendEmailResponse,
    undefined,
    AuthControllerTestSendEmailVariables
  >(
    (variables: AuthControllerTestSendEmailVariables) =>
      fetchAuthControllerTestSendEmail({ ...fetcherOptions, ...variables }),
    options
  );
};

export type UsersControllerGetAllUsersQueryParams = {
  /*
   * How many items to retrieve (min: 1, default: 10):
   */
  limit?: void;
  /*
   * How many items to skip from beggining of list:
   */
  offset?: void;
};

export type UsersControllerGetAllUsersResponse = {
  success: boolean;
  /*
   * @default false
   */
  isArray: boolean;
  isPaginated?: boolean;
  isSorted?: boolean;
  isFiltered?: boolean;
  message?: string;
  pagination?: Schemas.PaginationInfoDto;
  sorting?: Schemas.SortingInfoDto;
  filtering?: Schemas.FilteringInfoDto;
  data: never;
};

export type UsersControllerGetAllUsersVariables = {
  queryParams?: UsersControllerGetAllUsersQueryParams;
} & BarsApiContext["fetcherOptions"];

export const fetchUsersControllerGetAllUsers = (
  variables: UsersControllerGetAllUsersVariables
) =>
  barsApiFetch<
    UsersControllerGetAllUsersResponse,
    undefined,
    {},
    UsersControllerGetAllUsersQueryParams,
    {}
  >({ url: "/api/users", method: "get", ...variables });

export const useUsersControllerGetAllUsers = (
  queryKey: reactQuery.QueryKey,
  variables: UsersControllerGetAllUsersVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      UsersControllerGetAllUsersResponse,
      undefined,
      UsersControllerGetAllUsersResponse
    >,
    "queryKey" | "queryFn"
  >
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } = useBarsApiContext();
  return reactQuery.useQuery<
    UsersControllerGetAllUsersResponse,
    undefined,
    UsersControllerGetAllUsersResponse
  >(
    queryKeyFn(queryKey),
    () => fetchUsersControllerGetAllUsers({ ...fetcherOptions, ...variables }),
    {
      ...queryOptions,
      ...options,
    }
  );
};

export type UsersControllerGetUserByIdPathParams = {
  id: string;
};

export type UsersControllerGetUserByIdResponse = {
  success: boolean;
  /*
   * @default false
   */
  isArray: boolean;
  isPaginated?: boolean;
  isSorted?: boolean;
  isFiltered?: boolean;
  message?: string;
  pagination?: Schemas.PaginationInfoDto;
  sorting?: Schemas.SortingInfoDto;
  filtering?: Schemas.FilteringInfoDto;
  data: Schemas.UserDto;
};

export type UsersControllerGetUserByIdVariables = {
  pathParams: UsersControllerGetUserByIdPathParams;
} & BarsApiContext["fetcherOptions"];

export const fetchUsersControllerGetUserById = (
  variables: UsersControllerGetUserByIdVariables
) =>
  barsApiFetch<
    UsersControllerGetUserByIdResponse,
    undefined,
    {},
    {},
    UsersControllerGetUserByIdPathParams
  >({ url: "/api/users/{id}", method: "get", ...variables });

export const useUsersControllerGetUserById = (
  queryKey: reactQuery.QueryKey,
  variables: UsersControllerGetUserByIdVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      UsersControllerGetUserByIdResponse,
      undefined,
      UsersControllerGetUserByIdResponse
    >,
    "queryKey" | "queryFn"
  >
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } = useBarsApiContext();
  return reactQuery.useQuery<
    UsersControllerGetUserByIdResponse,
    undefined,
    UsersControllerGetUserByIdResponse
  >(
    queryKeyFn(queryKey),
    () => fetchUsersControllerGetUserById({ ...fetcherOptions, ...variables }),
    {
      ...queryOptions,
      ...options,
    }
  );
};

export type StorageControllerUploadFileResponse = {
  success: boolean;
  /*
   * @default false
   */
  isArray: boolean;
  isPaginated?: boolean;
  isSorted?: boolean;
  isFiltered?: boolean;
  message?: string;
  pagination?: Schemas.PaginationInfoDto;
  sorting?: Schemas.SortingInfoDto;
  filtering?: Schemas.FilteringInfoDto;
  data: Record<string, any>;
};

export type StorageControllerUploadFileVariables =
  BarsApiContext["fetcherOptions"];

export const fetchStorageControllerUploadFile = (
  variables: StorageControllerUploadFileVariables
) =>
  barsApiFetch<StorageControllerUploadFileResponse, undefined, {}, {}, {}>({
    url: "/api/storage/upload",
    method: "post",
    ...variables,
  });

export const useStorageControllerUploadFile = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      StorageControllerUploadFileResponse,
      undefined,
      StorageControllerUploadFileVariables
    >,
    "mutationFn"
  >
) => {
  const { fetcherOptions } = useBarsApiContext();
  return reactQuery.useMutation<
    StorageControllerUploadFileResponse,
    undefined,
    StorageControllerUploadFileVariables
  >(
    (variables: StorageControllerUploadFileVariables) =>
      fetchStorageControllerUploadFile({ ...fetcherOptions, ...variables }),
    options
  );
};

export type StorageControllerDownloadFilePathParams = {
  fileName: string;
};

export type StorageControllerDownloadFileResponse = {
  success: boolean;
  /*
   * @default false
   */
  isArray: boolean;
  isPaginated?: boolean;
  isSorted?: boolean;
  isFiltered?: boolean;
  message?: string;
  pagination?: Schemas.PaginationInfoDto;
  sorting?: Schemas.SortingInfoDto;
  filtering?: Schemas.FilteringInfoDto;
  data: Record<string, any>;
};

export type StorageControllerDownloadFileVariables = {
  pathParams: StorageControllerDownloadFilePathParams;
} & BarsApiContext["fetcherOptions"];

export const fetchStorageControllerDownloadFile = (
  variables: StorageControllerDownloadFileVariables
) =>
  barsApiFetch<
    StorageControllerDownloadFileResponse,
    undefined,
    {},
    {},
    StorageControllerDownloadFilePathParams
  >({ url: "/api/storage/download/{fileName}", method: "get", ...variables });

export const useStorageControllerDownloadFile = (
  queryKey: reactQuery.QueryKey,
  variables: StorageControllerDownloadFileVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      StorageControllerDownloadFileResponse,
      undefined,
      StorageControllerDownloadFileResponse
    >,
    "queryKey" | "queryFn"
  >
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } = useBarsApiContext();
  return reactQuery.useQuery<
    StorageControllerDownloadFileResponse,
    undefined,
    StorageControllerDownloadFileResponse
  >(
    queryKeyFn(queryKey),
    () =>
      fetchStorageControllerDownloadFile({ ...fetcherOptions, ...variables }),
    {
      ...queryOptions,
      ...options,
    }
  );
};

export type StorageControllerDeleteFilePathParams = {
  fileName: string;
};

export type StorageControllerDeleteFileResponse = {
  success: boolean;
  /*
   * @default false
   */
  isArray: boolean;
  isPaginated?: boolean;
  isSorted?: boolean;
  isFiltered?: boolean;
  message?: string;
  pagination?: Schemas.PaginationInfoDto;
  sorting?: Schemas.SortingInfoDto;
  filtering?: Schemas.FilteringInfoDto;
  data: Record<string, any>;
};

export type StorageControllerDeleteFileVariables = {
  pathParams: StorageControllerDeleteFilePathParams;
} & BarsApiContext["fetcherOptions"];

export const fetchStorageControllerDeleteFile = (
  variables: StorageControllerDeleteFileVariables
) =>
  barsApiFetch<
    StorageControllerDeleteFileResponse,
    undefined,
    {},
    {},
    StorageControllerDeleteFilePathParams
  >({ url: "/api/storage/{fileName}", method: "delete", ...variables });

export const useStorageControllerDeleteFile = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      StorageControllerDeleteFileResponse,
      undefined,
      StorageControllerDeleteFileVariables
    >,
    "mutationFn"
  >
) => {
  const { fetcherOptions } = useBarsApiContext();
  return reactQuery.useMutation<
    StorageControllerDeleteFileResponse,
    undefined,
    StorageControllerDeleteFileVariables
  >(
    (variables: StorageControllerDeleteFileVariables) =>
      fetchStorageControllerDeleteFile({ ...fetcherOptions, ...variables }),
    options
  );
};

export type StorageControllerListFilesQueryParams = {
  /*
   * How many items to retrieve (min: 1, default: 10):
   */
  limit?: void;
  /*
   * How many items to skip from beggining of list:
   */
  offset?: void;
};

export type StorageControllerListFilesResponse = {
  success: boolean;
  /*
   * @default false
   */
  isArray: boolean;
  isPaginated?: boolean;
  isSorted?: boolean;
  isFiltered?: boolean;
  message?: string;
  pagination?: Schemas.PaginationInfoDto;
  sorting?: Schemas.SortingInfoDto;
  filtering?: Schemas.FilteringInfoDto;
  data: never;
};

export type StorageControllerListFilesVariables = {
  queryParams?: StorageControllerListFilesQueryParams;
} & BarsApiContext["fetcherOptions"];

export const fetchStorageControllerListFiles = (
  variables: StorageControllerListFilesVariables
) =>
  barsApiFetch<
    StorageControllerListFilesResponse,
    undefined,
    {},
    StorageControllerListFilesQueryParams,
    {}
  >({ url: "/api/storage/list", method: "get", ...variables });

export const useStorageControllerListFiles = (
  queryKey: reactQuery.QueryKey,
  variables: StorageControllerListFilesVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      StorageControllerListFilesResponse,
      undefined,
      StorageControllerListFilesResponse
    >,
    "queryKey" | "queryFn"
  >
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } = useBarsApiContext();
  return reactQuery.useQuery<
    StorageControllerListFilesResponse,
    undefined,
    StorageControllerListFilesResponse
  >(
    queryKeyFn(queryKey),
    () => fetchStorageControllerListFiles({ ...fetcherOptions, ...variables }),
    {
      ...queryOptions,
      ...options,
    }
  );
};

export type StorageControllerCheckFileExistsPathParams = {
  fileName: string;
};

export type StorageControllerCheckFileExistsResponse = {
  success: boolean;
  /*
   * @default false
   */
  isArray: boolean;
  isPaginated?: boolean;
  isSorted?: boolean;
  isFiltered?: boolean;
  message?: string;
  pagination?: Schemas.PaginationInfoDto;
  sorting?: Schemas.SortingInfoDto;
  filtering?: Schemas.FilteringInfoDto;
  data: Record<string, any>;
};

export type StorageControllerCheckFileExistsVariables = {
  pathParams: StorageControllerCheckFileExistsPathParams;
} & BarsApiContext["fetcherOptions"];

export const fetchStorageControllerCheckFileExists = (
  variables: StorageControllerCheckFileExistsVariables
) =>
  barsApiFetch<
    StorageControllerCheckFileExistsResponse,
    undefined,
    {},
    {},
    StorageControllerCheckFileExistsPathParams
  >({ url: "/api/storage/exists/{fileName}", method: "get", ...variables });

export const useStorageControllerCheckFileExists = (
  queryKey: reactQuery.QueryKey,
  variables: StorageControllerCheckFileExistsVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      StorageControllerCheckFileExistsResponse,
      undefined,
      StorageControllerCheckFileExistsResponse
    >,
    "queryKey" | "queryFn"
  >
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } = useBarsApiContext();
  return reactQuery.useQuery<
    StorageControllerCheckFileExistsResponse,
    undefined,
    StorageControllerCheckFileExistsResponse
  >(
    queryKeyFn(queryKey),
    () =>
      fetchStorageControllerCheckFileExists({
        ...fetcherOptions,
        ...variables,
      }),
    {
      ...queryOptions,
      ...options,
    }
  );
};

export type StorageControllerGetSignedUrlPathParams = {
  fileName: string;
};

export type StorageControllerGetSignedUrlResponse = {
  success: boolean;
  /*
   * @default false
   */
  isArray: boolean;
  isPaginated?: boolean;
  isSorted?: boolean;
  isFiltered?: boolean;
  message?: string;
  pagination?: Schemas.PaginationInfoDto;
  sorting?: Schemas.SortingInfoDto;
  filtering?: Schemas.FilteringInfoDto;
  data: Record<string, any>;
};

export type StorageControllerGetSignedUrlVariables = {
  pathParams: StorageControllerGetSignedUrlPathParams;
} & BarsApiContext["fetcherOptions"];

export const fetchStorageControllerGetSignedUrl = (
  variables: StorageControllerGetSignedUrlVariables
) =>
  barsApiFetch<
    StorageControllerGetSignedUrlResponse,
    undefined,
    {},
    {},
    StorageControllerGetSignedUrlPathParams
  >({ url: "/api/storage/signed-url/{fileName}", method: "get", ...variables });

export const useStorageControllerGetSignedUrl = (
  queryKey: reactQuery.QueryKey,
  variables: StorageControllerGetSignedUrlVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      StorageControllerGetSignedUrlResponse,
      undefined,
      StorageControllerGetSignedUrlResponse
    >,
    "queryKey" | "queryFn"
  >
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } = useBarsApiContext();
  return reactQuery.useQuery<
    StorageControllerGetSignedUrlResponse,
    undefined,
    StorageControllerGetSignedUrlResponse
  >(
    queryKeyFn(queryKey),
    () =>
      fetchStorageControllerGetSignedUrl({ ...fetcherOptions, ...variables }),
    {
      ...queryOptions,
      ...options,
    }
  );
};

export type ThesaurusControllerSearchQueryParams = {
  q: string;
  limit: string;
};

export type ThesaurusControllerSearchResponse = {
  success: boolean;
  /*
   * @default false
   */
  isArray: boolean;
  isPaginated?: boolean;
  isSorted?: boolean;
  isFiltered?: boolean;
  message?: string;
  pagination?: Schemas.PaginationInfoDto;
  sorting?: Schemas.SortingInfoDto;
  filtering?: Schemas.FilteringInfoDto;
  data: never;
};

export type ThesaurusControllerSearchVariables = {
  queryParams: ThesaurusControllerSearchQueryParams;
} & BarsApiContext["fetcherOptions"];

export const fetchThesaurusControllerSearch = (
  variables: ThesaurusControllerSearchVariables
) =>
  barsApiFetch<
    ThesaurusControllerSearchResponse,
    undefined,
    {},
    ThesaurusControllerSearchQueryParams,
    {}
  >({ url: "/api/api/v1/thesaurus/search", method: "get", ...variables });

export const useThesaurusControllerSearch = (
  queryKey: reactQuery.QueryKey,
  variables: ThesaurusControllerSearchVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      ThesaurusControllerSearchResponse,
      undefined,
      ThesaurusControllerSearchResponse
    >,
    "queryKey" | "queryFn"
  >
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } = useBarsApiContext();
  return reactQuery.useQuery<
    ThesaurusControllerSearchResponse,
    undefined,
    ThesaurusControllerSearchResponse
  >(
    queryKeyFn(queryKey),
    () => fetchThesaurusControllerSearch({ ...fetcherOptions, ...variables }),
    {
      ...queryOptions,
      ...options,
    }
  );
};

export type ThesaurusControllerDetailsPathParams = {
  word: string;
};

export type ThesaurusControllerDetailsResponse = {
  success: boolean;
  /*
   * @default false
   */
  isArray: boolean;
  isPaginated?: boolean;
  isSorted?: boolean;
  isFiltered?: boolean;
  message?: string;
  pagination?: Schemas.PaginationInfoDto;
  sorting?: Schemas.SortingInfoDto;
  filtering?: Schemas.FilteringInfoDto;
  data: never;
};

export type ThesaurusControllerDetailsVariables = {
  pathParams: ThesaurusControllerDetailsPathParams;
} & BarsApiContext["fetcherOptions"];

export const fetchThesaurusControllerDetails = (
  variables: ThesaurusControllerDetailsVariables
) =>
  barsApiFetch<
    ThesaurusControllerDetailsResponse,
    undefined,
    {},
    {},
    ThesaurusControllerDetailsPathParams
  >({ url: "/api/api/v1/thesaurus/words/{word}", method: "get", ...variables });

export const useThesaurusControllerDetails = (
  queryKey: reactQuery.QueryKey,
  variables: ThesaurusControllerDetailsVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      ThesaurusControllerDetailsResponse,
      undefined,
      ThesaurusControllerDetailsResponse
    >,
    "queryKey" | "queryFn"
  >
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } = useBarsApiContext();
  return reactQuery.useQuery<
    ThesaurusControllerDetailsResponse,
    undefined,
    ThesaurusControllerDetailsResponse
  >(
    queryKeyFn(queryKey),
    () => fetchThesaurusControllerDetails({ ...fetcherOptions, ...variables }),
    {
      ...queryOptions,
      ...options,
    }
  );
};

export type ThesaurusControllerRhymesPathParams = {
  word: string;
};

export type ThesaurusControllerRhymesQueryParams = {
  limit: string;
  offset: string;
  type: string;
  randomness: string;
};

export type ThesaurusControllerRhymesResponse = {
  success: boolean;
  /*
   * @default false
   */
  isArray: boolean;
  isPaginated?: boolean;
  isSorted?: boolean;
  isFiltered?: boolean;
  message?: string;
  pagination?: Schemas.PaginationInfoDto;
  sorting?: Schemas.SortingInfoDto;
  filtering?: Schemas.FilteringInfoDto;
  data: never;
};

export type ThesaurusControllerRhymesVariables = {
  pathParams: ThesaurusControllerRhymesPathParams;
  queryParams: ThesaurusControllerRhymesQueryParams;
} & BarsApiContext["fetcherOptions"];

export const fetchThesaurusControllerRhymes = (
  variables: ThesaurusControllerRhymesVariables
) =>
  barsApiFetch<
    ThesaurusControllerRhymesResponse,
    undefined,
    {},
    ThesaurusControllerRhymesQueryParams,
    ThesaurusControllerRhymesPathParams
  >({
    url: "/api/api/v1/thesaurus/words/{word}/rhymes",
    method: "get",
    ...variables,
  });

export const useThesaurusControllerRhymes = (
  queryKey: reactQuery.QueryKey,
  variables: ThesaurusControllerRhymesVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      ThesaurusControllerRhymesResponse,
      undefined,
      ThesaurusControllerRhymesResponse
    >,
    "queryKey" | "queryFn"
  >
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } = useBarsApiContext();
  return reactQuery.useQuery<
    ThesaurusControllerRhymesResponse,
    undefined,
    ThesaurusControllerRhymesResponse
  >(
    queryKeyFn(queryKey),
    () => fetchThesaurusControllerRhymes({ ...fetcherOptions, ...variables }),
    {
      ...queryOptions,
      ...options,
    }
  );
};

export type ThesaurusControllerRelatedPathParams = {
  word: string;
};

export type ThesaurusControllerRelatedQueryParams = {
  group: string;
};

export type ThesaurusControllerRelatedResponse = {
  success: boolean;
  /*
   * @default false
   */
  isArray: boolean;
  isPaginated?: boolean;
  isSorted?: boolean;
  isFiltered?: boolean;
  message?: string;
  pagination?: Schemas.PaginationInfoDto;
  sorting?: Schemas.SortingInfoDto;
  filtering?: Schemas.FilteringInfoDto;
  data: never;
};

export type ThesaurusControllerRelatedVariables = {
  pathParams: ThesaurusControllerRelatedPathParams;
  queryParams: ThesaurusControllerRelatedQueryParams;
} & BarsApiContext["fetcherOptions"];

export const fetchThesaurusControllerRelated = (
  variables: ThesaurusControllerRelatedVariables
) =>
  barsApiFetch<
    ThesaurusControllerRelatedResponse,
    undefined,
    {},
    ThesaurusControllerRelatedQueryParams,
    ThesaurusControllerRelatedPathParams
  >({
    url: "/api/api/v1/thesaurus/words/{word}/related",
    method: "get",
    ...variables,
  });

export const useThesaurusControllerRelated = (
  queryKey: reactQuery.QueryKey,
  variables: ThesaurusControllerRelatedVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      ThesaurusControllerRelatedResponse,
      undefined,
      ThesaurusControllerRelatedResponse
    >,
    "queryKey" | "queryFn"
  >
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } = useBarsApiContext();
  return reactQuery.useQuery<
    ThesaurusControllerRelatedResponse,
    undefined,
    ThesaurusControllerRelatedResponse
  >(
    queryKeyFn(queryKey),
    () => fetchThesaurusControllerRelated({ ...fetcherOptions, ...variables }),
    {
      ...queryOptions,
      ...options,
    }
  );
};

export type ThesaurusControllerWordplayPathParams = {
  /*
   * Headword to generate wordplay for
   */
  word: string;
};

export type ThesaurusControllerWordplayResponse = {
  success: boolean;
  /*
   * @default false
   */
  isArray: boolean;
  isPaginated?: boolean;
  isSorted?: boolean;
  isFiltered?: boolean;
  message?: string;
  pagination?: Schemas.PaginationInfoDto;
  sorting?: Schemas.SortingInfoDto;
  filtering?: Schemas.FilteringInfoDto;
  data: never;
};

export type ThesaurusControllerWordplayVariables = {
  body?: Schemas.GenerateWordplayDto;
  pathParams: ThesaurusControllerWordplayPathParams;
} & BarsApiContext["fetcherOptions"];

export const fetchThesaurusControllerWordplay = (
  variables: ThesaurusControllerWordplayVariables
) =>
  barsApiFetch<
    ThesaurusControllerWordplayResponse,
    Schemas.GenerateWordplayDto,
    {},
    {},
    ThesaurusControllerWordplayPathParams
  >({
    url: "/api/api/v1/thesaurus/words/{word}/wordplay",
    method: "post",
    ...variables,
  });

export const useThesaurusControllerWordplay = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      ThesaurusControllerWordplayResponse,
      undefined,
      ThesaurusControllerWordplayVariables
    >,
    "mutationFn"
  >
) => {
  const { fetcherOptions } = useBarsApiContext();
  return reactQuery.useMutation<
    ThesaurusControllerWordplayResponse,
    undefined,
    ThesaurusControllerWordplayVariables
  >(
    (variables: ThesaurusControllerWordplayVariables) =>
      fetchThesaurusControllerWordplay({ ...fetcherOptions, ...variables }),
    options
  );
};

export type ThesaurusControllerExamplesPathParams = {
  word: string;
};

export type ThesaurusControllerExamplesVariables = {
  pathParams: ThesaurusControllerExamplesPathParams;
} & BarsApiContext["fetcherOptions"];

export const fetchThesaurusControllerExamples = (
  variables: ThesaurusControllerExamplesVariables
) =>
  barsApiFetch<
    undefined,
    undefined,
    {},
    {},
    ThesaurusControllerExamplesPathParams
  >({
    url: "/api/api/v1/thesaurus/words/{word}/examples",
    method: "get",
    ...variables,
  });

export const useThesaurusControllerExamples = (
  queryKey: reactQuery.QueryKey,
  variables: ThesaurusControllerExamplesVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<undefined, undefined, undefined>,
    "queryKey" | "queryFn"
  >
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } = useBarsApiContext();
  return reactQuery.useQuery<undefined, undefined, undefined>(
    queryKeyFn(queryKey),
    () => fetchThesaurusControllerExamples({ ...fetcherOptions, ...variables }),
    {
      ...queryOptions,
      ...options,
    }
  );
};

export type RapControllerGenerateResponse = {
  success: boolean;
  /*
   * @default false
   */
  isArray: boolean;
  isPaginated?: boolean;
  isSorted?: boolean;
  isFiltered?: boolean;
  message?: string;
  pagination?: Schemas.PaginationInfoDto;
  sorting?: Schemas.SortingInfoDto;
  filtering?: Schemas.FilteringInfoDto;
  data: never;
};

export type RapControllerGenerateVariables = {
  body: Schemas.GenerateRapDto;
} & BarsApiContext["fetcherOptions"];

export const fetchRapControllerGenerate = (
  variables: RapControllerGenerateVariables
) =>
  barsApiFetch<
    RapControllerGenerateResponse,
    Schemas.GenerateRapDto,
    {},
    {},
    {}
  >({ url: "/api/api/v1/sonauto/rap/generate", method: "post", ...variables });

export const useRapControllerGenerate = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      RapControllerGenerateResponse,
      undefined,
      RapControllerGenerateVariables
    >,
    "mutationFn"
  >
) => {
  const { fetcherOptions } = useBarsApiContext();
  return reactQuery.useMutation<
    RapControllerGenerateResponse,
    undefined,
    RapControllerGenerateVariables
  >(
    (variables: RapControllerGenerateVariables) =>
      fetchRapControllerGenerate({ ...fetcherOptions, ...variables }),
    options
  );
};

export type RapControllerGenerateAndWaitResponse = {
  success: boolean;
  /*
   * @default false
   */
  isArray: boolean;
  isPaginated?: boolean;
  isSorted?: boolean;
  isFiltered?: boolean;
  message?: string;
  pagination?: Schemas.PaginationInfoDto;
  sorting?: Schemas.SortingInfoDto;
  filtering?: Schemas.FilteringInfoDto;
  data: never;
};

export type RapControllerGenerateAndWaitVariables = {
  body: Schemas.GenerateRapDto;
} & BarsApiContext["fetcherOptions"];

export const fetchRapControllerGenerateAndWait = (
  variables: RapControllerGenerateAndWaitVariables
) =>
  barsApiFetch<
    RapControllerGenerateAndWaitResponse,
    Schemas.GenerateRapDto,
    {},
    {},
    {}
  >({
    url: "/api/api/v1/sonauto/rap/generate_and_wait",
    method: "post",
    ...variables,
  });

export const useRapControllerGenerateAndWait = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      RapControllerGenerateAndWaitResponse,
      undefined,
      RapControllerGenerateAndWaitVariables
    >,
    "mutationFn"
  >
) => {
  const { fetcherOptions } = useBarsApiContext();
  return reactQuery.useMutation<
    RapControllerGenerateAndWaitResponse,
    undefined,
    RapControllerGenerateAndWaitVariables
  >(
    (variables: RapControllerGenerateAndWaitVariables) =>
      fetchRapControllerGenerateAndWait({ ...fetcherOptions, ...variables }),
    options
  );
};

export type RapControllerStatusPathParams = {
  taskId: string;
};

export type RapControllerStatusResponse = {
  success: boolean;
  /*
   * @default false
   */
  isArray: boolean;
  isPaginated?: boolean;
  isSorted?: boolean;
  isFiltered?: boolean;
  message?: string;
  pagination?: Schemas.PaginationInfoDto;
  sorting?: Schemas.SortingInfoDto;
  filtering?: Schemas.FilteringInfoDto;
  data: never;
};

export type RapControllerStatusVariables = {
  pathParams: RapControllerStatusPathParams;
} & BarsApiContext["fetcherOptions"];

export const fetchRapControllerStatus = (
  variables: RapControllerStatusVariables
) =>
  barsApiFetch<
    RapControllerStatusResponse,
    undefined,
    {},
    {},
    RapControllerStatusPathParams
  >({
    url: "/api/api/v1/sonauto/rap/status/{taskId}",
    method: "get",
    ...variables,
  });

export const useRapControllerStatus = (
  queryKey: reactQuery.QueryKey,
  variables: RapControllerStatusVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      RapControllerStatusResponse,
      undefined,
      RapControllerStatusResponse
    >,
    "queryKey" | "queryFn"
  >
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } = useBarsApiContext();
  return reactQuery.useQuery<
    RapControllerStatusResponse,
    undefined,
    RapControllerStatusResponse
  >(
    queryKeyFn(queryKey),
    () => fetchRapControllerStatus({ ...fetcherOptions, ...variables }),
    {
      ...queryOptions,
      ...options,
    }
  );
};

export type RapControllerStreamEventsQueryParams = {
  /*
   * Task id to subscribe to
   */
  taskId: string;
};

export type RapControllerStreamEventsVariables = {
  queryParams: RapControllerStreamEventsQueryParams;
} & BarsApiContext["fetcherOptions"];

export const fetchRapControllerStreamEvents = (
  variables: RapControllerStreamEventsVariables
) =>
  barsApiFetch<
    undefined,
    undefined,
    {},
    RapControllerStreamEventsQueryParams,
    {}
  >({ url: "/api/api/v1/sonauto/rap/events", method: "get", ...variables });

export const useRapControllerStreamEvents = (
  queryKey: reactQuery.QueryKey,
  variables: RapControllerStreamEventsVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<undefined, undefined, undefined>,
    "queryKey" | "queryFn"
  >
) => {
  const { fetcherOptions, queryOptions, queryKeyFn } = useBarsApiContext();
  return reactQuery.useQuery<undefined, undefined, undefined>(
    queryKeyFn(queryKey),
    () => fetchRapControllerStreamEvents({ ...fetcherOptions, ...variables }),
    {
      ...queryOptions,
      ...options,
    }
  );
};
