/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
export type PaginationInfoDto = {
  query?: string;
  count?: number;
  limit: number;
  offset: number;
  maxLimit?: number;
  minLimit?: number;
  defaultLimit?: number;
};

export type SortingInfoDto = {
  query?: string;
  sort?: string[];
  sortableFields?: string[];
};

export type FilteringInfoDto = {
  query?: string;
  filter?: Record<string, any>;
  filterableFields?: string[];
};

export type StandardResponseDto = {
  success: boolean;
  /*
   * @default false
   */
  isArray: boolean;
  isPaginated?: boolean;
  isSorted?: boolean;
  isFiltered?: boolean;
  message?: string;
  pagination?: PaginationInfoDto;
  sorting?: SortingInfoDto;
  filtering?: FilteringInfoDto;
  data: Record<string, any>;
};

export type RegisterDto = {};

export type AuthResponseDto = {};

export type LoginDto = {};

export type ChangePasswordDto = {};

export type ForgotPasswordDto = {};

export type ResetPasswordDto = {};

export type GenerateWordplayDto = {
  /*
   * Tone of the output
   *
   * @example Poetic
   */
  tone?: "Poetic" | "Street" | "Deep";
  /*
   * Context or topic to seed the generation
   *
   * @example Gugma (Love)
   */
  context?: string;
  /*
   * Figurative style to prefer
   *
   * @example Metaphor
   */
  figurativeStyle?: "Metaphor" | "Simile" | "Personification";
  /*
   * Preferred length of each generated item
   *
   * @example short
   */
  length?: "short" | "medium" | "long";
  /*
   * Number of results to return (1-5)
   *
   * @example 1
   */
  num_results?: number;
  /*
   * Preferred rhyme scheme for generated lines
   *
   * @example AABB
   */
  rhymeScheme?: "AABB" | "ABAB" | "ABBA" | "AAAA" | "Couplet" | "Free" | "None";
};

export type GenerateRapDto = {
  /*
   * Lyrics or seed text to guide the rap generation
   *
   * @example Gugma sa kalsada
   */
  lyrics: string;
  /*
   * Beats per minute or "auto"
   *
   * @example 90
   */
  bpm?: Record<string, any>;
  /*
   * Number of results to generate (1-2)
   *
   * @example 1
   */
  num_songs?: number;
  /*
   * Desired output format
   *
   * @example ogg
   */
  output_format?: "mp3" | "flac" | "wav" | "ogg" | "m4a";
};
