/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
export type PaginationInfoDto = {
  query?: string;
  count?: number;
  limit: number;
  offset: number;
  maxLimit?: number;
  minLimit?: number;
  defaultLimit?: number;
};

export type SortingInfoDto = {
  query?: string;
  sort?: string[];
  sortableFields?: string[];
};

export type FilteringInfoDto = {
  query?: string;
  filter?: Record<string, any>;
  filterableFields?: string[];
};

export type StandardResponseDto = {
  success: boolean;
  /*
   * @default false
   */
  isArray: boolean;
  isPaginated?: boolean;
  isSorted?: boolean;
  isFiltered?: boolean;
  message?: string;
  pagination?: PaginationInfoDto;
  sorting?: SortingInfoDto;
  filtering?: FilteringInfoDto;
  data: Record<string, any>;
};

export type AuthResponseDto = {
  /*
   * @example user_abc123
   */
  id: string;
  /*
   * @example alice@example.com
   */
  email: string;
  /*
   * @example alice
   */
  username: string;
  /*
   * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
   */
  token: string;
  /*
   * Refresh token is also set in cookie; included here for convenience
   *
   * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
   */
  refreshToken?: string;
};

export type RegisterDto = {
  /*
   * @example alice@example.com
   */
  email: string;
  /*
   * @example alice
   */
  username: string;
  /*
   * @example SecretPass123
   */
  password: string;
};

export type LoginDto = {
  /*
   * @example alice@example.com
   */
  email: string;
  /*
   * @example SecretPass123
   */
  password: string;
};

export type ChangePasswordDto = {
  /*
   * @example OldPassword123
   */
  current_password: string;
  /*
   * @example NewPassword123
   */
  new_password: string;
};

export type ForgotPasswordDto = {
  /*
   * @example alice@example.com
   */
  email: string;
};

export type ResetPasswordDto = {
  /*
   * @example f1e2d3c4b5a6...
   */
  token: string;
  /*
   * @example NewPassword123
   */
  new_password: string;
};

export type UserDto = {
  id: string;
  email: string;
  username: string;
};

export type GenerateWordplayDto = {
  /*
   * Tone of the output
   *
   * @example Poetic
   */
  tone?: "Poetic" | "Street" | "Deep";
  /*
   * Context or topic to seed the generation
   *
   * @example Gugma (Love)
   */
  context?: string;
  /*
   * Figurative style to prefer
   *
   * @example Metaphor
   */
  figurative_style?: "Metaphor" | "Simile" | "Personification";
  /*
   * Preferred length of each generated item
   *
   * @example short
   */
  length?: "short" | "medium" | "long";
  /*
   * Number of results to return (1-5)
   *
   * @example 1
   */
  num_results?: number;
  /*
   * Preferred rhyme scheme for generated lines
   *
   * @example AABB
   */
  rhyme_scheme?:
    | "AABB"
    | "ABAB"
    | "ABBA"
    | "AAAA"
    | "Couplet"
    | "Free"
    | "None";
};

export type GenerateRapDto = {
  /*
   * Lyrics or seed text to guide the rap generation
   *
   * @example Gugma sa kalsada
   */
  lyrics: string;
  /*
   * Beats per minute or "auto"
   *
   * @example 90
   */
  bpm?: Record<string, any>;
  /*
   * Number of results to generate (1-2)
   *
   * @example 1
   */
  num_songs?: number;
  /*
   * Desired output format
   *
   * @example ogg
   */
  output_format?: "mp3" | "flac" | "wav" | "ogg" | "m4a";
};
