import type { Metadata } from "next";
import { Geist, Geist_Mono, Be_Vietnam_Pro } from "next/font/google";
import "./globals.css";

import ReactQueryProvider from "@/components/ReactQueryProvider";
import { ToastProvider } from "@/contexts/toast";
import ToastContainer from "@/components/organisms/ToastContainer";
import { SettingsProvider } from "@/contexts/settings";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const beVietnam = Be_Vietnam_Pro({
  weight: ["400","700","900"],
  subsets: ["latin"],
  variable: "--font-display",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap" rel="stylesheet" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${beVietnam.variable} antialiased dark`}
      >
        {/* React Query provider (client) */}
        {/* Wrapped with ToastProvider so any component can call useToast() */}
        <ReactQueryProvider>
          <ToastProvider>
            <SettingsProvider>
              <ToastContainer />
              {children}
            </SettingsProvider>
          </ToastProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
